pacman::p_load(
  here,
  tidyverse
)

# Individual-level simulated time-varying data (N = 1,000,000)
# Generated by data_gen.R from a causal structure with two time-points:
#   Z0 -> A0 -> Z1 -> A1 -> Y
#        Z0 -> Z1;   Z0 -> Y;   A0 -> Y;   A1 -> Y
d <- read_csv(here("data", "time_varying_data.csv"))

# ── ICE g-formula: two-timepoint time-varying confounding ─────────────────
#
# Causal estimand:
#   psi = E(Y^{a0=1,a1=1}) - E(Y^{a0=0,a1=0})
#
# ICE identification formula (equation 2 in the manuscript):
#   E(Y^{a0,a1}) = E{ E[ E(Y | Z0, A0=a0, Z1, A1=a1) | Z0, A0=a0 ] }
#
# The three nested expectations are estimated via backward recursion,
# working from the inside out over three sequential regression steps.
#
# NOTE: Unlike NICE, ICE does not require a model for the time-varying
# confounder Z1. This makes ICE robust to misspecification of the Z1
# distribution, at the cost of requiring a correctly specified outcome model.

# ── Step 1: inner expectation ─────────────────────────────────────────────
# Fit E(Y | Z0, A0, Z1, A1); predict under each static intervention regime.
# These predictions are labeled Q1 in the backward recursion notation.
fit1    <- lm(y ~ z0 + a0 + z1 + a1, data = d)
d$Q1_11 <- predict(fit1, newdata = transform(d, a0 = 1, a1 = 1))
d$Q1_00 <- predict(fit1, newdata = transform(d, a0 = 0, a1 = 0))

# ── Step 2: middle expectation ────────────────────────────────────────────
# Regress the Step 1 predictions on (Z0, A0) and predict under each a0.
# This marginalizes over the interventional distribution of Z1, replacing
# Z1 with its expected contribution given (Z0, A0=a0).
fit2_11 <- lm(Q1_11 ~ z0 + a0, data = d)
fit2_00 <- lm(Q1_00 ~ z0 + a0, data = d)
d$Q2_11 <- predict(fit2_11, newdata = transform(d, a0 = 1))
d$Q2_00 <- predict(fit2_00, newdata = transform(d, a0 = 0))

# ── Step 3: outer expectation ─────────────────────────────────────────────
# Average Q2 over the empirical marginal distribution of Z0.
# Under the identification assumptions this recovers E(Y^{a0,a1}).
E_Ya_11 <- mean(d$Q2_11)
E_Ya_00 <- mean(d$Q2_00)

cat("ICE  E(Y^{a0=1,a1=1}) =", round(E_Ya_11, 2), "\n")
cat("ICE  E(Y^{a0=0,a1=0}) =", round(E_Ya_00, 2), "\n")
cat("ICE  ATE              =", round(E_Ya_11 - E_Ya_00, 2), "\n")
