pacman::p_load(
  here,
  tidyverse
)

# Individual-level simulated time-varying data (N = 1,000,000)
# Generated by data_gen.R from a causal structure with two time-points:
#   Z0 -> A0 -> Z1 -> A1 -> Y
#        Z0 -> Z1;   Z0 -> Y;   A0 -> Y;   A1 -> Y
d <- read_csv(here("data", "time_varying_data.csv"))

# ── NICE g-formula: two-timepoint time-varying confounding ────────────────
#
# Causal estimand:
#   psi = E(Y^{a0=1,a1=1}) - E(Y^{a0=0,a1=0})
#
# NICE identification formula (equation 1 in the manuscript):
#   E(Y^{a0,a1}) = sum_{z0} sum_{z1} E(Y | Z0=z0, A0=a0, Z1=z1, A1=a1)
#                                   x P(Z1=z1 | Z0=z0, A0=a0)
#                                   x P(Z0=z0)
#
# In individual-level form: for each individual i (with observed Z0_i),
# marginalize the outcome predictions over the interventional Z1 distribution
# P(Z1 | Z0_i, A0=a0_int), then average over the empirical distribution of Z0.
#
# NOTE: NICE requires an explicit model for the time-varying confounder Z1.
# Misspecification of this model introduces bias. ICE does not carry this
# requirement, which is often cited as an advantage of ICE over NICE.

# ── Step 1: Fit outcome model E(Y | Z0, A0, Z1, A1) ─────────────────────
fit_Y  <- lm(y ~ z0 + a0 + z1 + a1, data = d)

# ── Step 2: Fit Z1 nuisance model P(Z1=1 | Z0, A0) ──────────────────────
# The data-generating mechanism is:
#   P(Z1=1 | Z0, A0) = expit(-1 + log(1.5)*Z0 + log(1.5)*A0 + log(1.5)*Z0*A0)
# The Z0*A0 interaction is required here; omitting it misspecifies the model.
fit_Z1 <- glm(z1 ~ z0 * a0, family = binomial, data = d)

# ── Step 3: NICE estimator ────────────────────────────────────────────────
# For each individual i (with observed Z0_i):
#   1. Predict E(Y | Z0_i, a0_int, Z1=0, a1_int) and
#              E(Y | Z0_i, a0_int, Z1=1, a1_int)  from the outcome model
#   2. Predict P(Z1=1 | Z0_i, a0_int)              from the Z1 model
#   3. Form the Z1-marginalized prediction:
#        Q_i = (1 - pZ1_i) * Q_z1_0_i + pZ1_i * Q_z1_1_i
#   4. Average Q_i over all i to marginalize over Z0

nice_estimate <- function(a0_int, a1_int) {
  # Outcome predictions with Z1 fixed at 0 and 1
  Q_z1_0 <- predict(fit_Y, newdata = transform(d, a0 = a0_int, z1 = 0, a1 = a1_int))
  Q_z1_1 <- predict(fit_Y, newdata = transform(d, a0 = a0_int, z1 = 1, a1 = a1_int))

  # P(Z1=1 | Z0_i, A0=a0_int) for every individual
  pZ1 <- predict(fit_Z1, newdata = transform(d, a0 = a0_int), type = "response")

  # Marginalize over Z1, then over Z0
  mean((1 - pZ1) * Q_z1_0 + pZ1 * Q_z1_1)
}

E_Ya_11 <- nice_estimate(1, 1)
E_Ya_00 <- nice_estimate(0, 0)

cat("NICE E(Y^{a0=1,a1=1}) =", round(E_Ya_11, 2), "\n")
cat("NICE E(Y^{a0=0,a1=0}) =", round(E_Ya_00, 2), "\n")
cat("NICE ATE              =", round(E_Ya_11 - E_Ya_00, 2), "\n")

# ── Table-based verification ──────────────────────────────────────────────
# Reproduces the hand calculation from the manuscript (Section 5.1 / Table 4).
# Here the 16-row summary table, P(Z0), and P(Z1|Z0,A0) are all derived
# directly from the empirical data, so the result should match the paper's
# hand calculation (E(Y^{1,1}) ~ 153.57, E(Y^{0,0}) ~ 150.28, ATE ~ 3.29).

cat("\n── Table-based verification (reproduces manuscript hand calculation) ──\n")

d_tab <- d %>%
  group_by(z0, a0, z1, a1) %>%
  summarize(mean_y = mean(y), n = n(), .groups = "drop")

# P(Z0 = z0)
p_z0 <- d_tab %>%
  group_by(z0) %>%
  summarize(n_z0 = sum(n), .groups = "drop") %>%
  mutate(p_z0 = n_z0 / sum(n_z0))

# P(Z1 = z1 | Z0 = z0, A0 = a0)
p_z1 <- d_tab %>%
  group_by(z0, a0) %>%
  mutate(p_z1 = n / sum(n)) %>%
  ungroup() %>%
  select(z0, a0, z1, p_z1)

nice_table <- function(a0_int, a1_int) {
  d_tab %>%
    filter(a0 == a0_int, a1 == a1_int) %>%
    left_join(p_z1 %>% filter(a0 == a0_int), by = c("z0", "z1")) %>%
    left_join(p_z0, by = "z0") %>%
    summarize(E_Ya = sum(mean_y * p_z1 * p_z0)) %>%
    pull(E_Ya)
}

E_Ya_11_tab <- nice_table(1, 1)
E_Ya_00_tab <- nice_table(0, 0)

cat("NICE E(Y^{a0=1,a1=1}) =", round(E_Ya_11_tab, 2), "(table-based)\n")
cat("NICE E(Y^{a0=0,a1=0}) =", round(E_Ya_00_tab, 2), "(table-based)\n")
cat("NICE ATE              =", round(E_Ya_11_tab - E_Ya_00_tab, 2), "(table-based)\n")
